// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Ogo.Data;

#nullable disable

namespace Ogo.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20220528141641_RemoveRequiredRoom")]
    partial class RemoveRequiredRoom
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.5");

            modelBuilder.Entity("Ogo.Data.Models.Housing", b =>
                {
                    b.Property<int>("Number")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CountOfFloors")
                        .HasColumnType("INTEGER");

                    b.HasKey("Number");

                    b.ToTable("Housings");
                });

            modelBuilder.Entity("Ogo.Data.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CountOfPossibleStudents")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HousingNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("HousingNumber");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("Ogo.Data.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BirthDay")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateOfEnrollment")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberOfOrderOfEnrollment")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberOfOrderOfHostel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlaceOfBirth")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("RoomId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("Ogo.Data.Models.Room", b =>
                {
                    b.HasOne("Ogo.Data.Models.Housing", "Housing")
                        .WithMany("Rooms")
                        .HasForeignKey("HousingNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Housing");
                });

            modelBuilder.Entity("Ogo.Data.Models.Student", b =>
                {
                    b.HasOne("Ogo.Data.Models.Room", "Room")
                        .WithMany("Students")
                        .HasForeignKey("RoomId");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Ogo.Data.Models.Housing", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("Ogo.Data.Models.Room", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
